In [1]:
# import shutil
# shutil.move("kaggle.json", "C:\\Users\\atifs\\.kaggle\\kaggle.json")

In [2]:
# !kaggle datasets download -d mragpavank/heart-diseaseuci

In [3]:
# import zipfile
# with zipfile.ZipFile("heart-diseaseuci.zip" ,"r") as f:
#     f.extractall("heart_disease_data")

In [4]:
# # Install dependencies as needed:
# # pip install kagglehub[pandas-datasets]
# import kagglehub
# from kagglehub import KaggleDatasetAdapter

# # Set the path to the file you'd like to load
# file_path = "heart.csv"

# # Load the latest version
# df = kagglehub.dataset_load(
#   KaggleDatasetAdapter.PANDAS,
#   "ronitf/heart-disease-uci",
#   file_path,
#   # Provide any additional arguments like 
#   # sql_query or pandas_kwargs. See the 
#   # documenation for more information:
#   # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
# )

# print("First 5 records:", df.head())

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("E:/Codes/Machine_Learning/heart_disease_data/heart.csv")

In [7]:
df.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [9]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [13]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [14]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

C:\Users\atifs\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [15]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [16]:
# y_pred1_binary = np.where(y_pred1 >= 0.5, 1, 0)
# y_pred2_binary = np.where(y_pred2 >= 0.5, 1, 0)

# Binary Calssification

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Accuracy Score

In [20]:
print("Accuracy for Logistic Regression", accuracy_score(y_test, y_pred1))
print("Accuracy for Decision Trees", accuracy_score(y_test, y_pred2))

Accuracy for Logistic Regression 0.9016393442622951
Accuracy for Decision Trees 0.8360655737704918


# Confusion Matrix

In [22]:
confusion_matrix(y_test, y_pred1)

array([[26,  6],
       [ 0, 29]], dtype=int64)

In [23]:
print("Confusion Matrix - Logistic Regression")
pd.DataFrame(confusion_matrix(y_test, y_pred1), columns=list(range(0,2))) 

Confusion Matrix - Logistic Regression


0   1
0  26   6
1   0  29

In [24]:
confusion_matrix(y_test, y_pred2)

array([[24,  8],
       [ 2, 27]], dtype=int64)

In [25]:
print("Confusion Matrix - Decision Tree")
pd.DataFrame(confusion_matrix(y_test, y_pred2), columns=list(range(0,2)))

Confusion Matrix - Decision Tree


0   1
0  24   8
1   2  27

In [26]:
result = pd.DataFrame()
result["Actual"] = y_test
result["Logistic Regression Pred"] = y_pred1
result["Decision Tree Pred"] = y_pred2

In [27]:
result.sample(10)

Actual  Logistic Regression Pred  Decision Tree Pred
179       0                         0                   0
188       0                         1                   0
161       1                         1                   1
134       1                         1                   1
65        1                         1                   1
250       0                         0                   0
164       1                         1                   1
169       0                         0                   0
30        1                         1                   1
257       0                         0                   0

In [28]:
cm_logistic = confusion_matrix(y_test, y_pred1)

In [29]:
cm_logistic

array([[26,  6],
       [ 0, 29]], dtype=int64)

In [30]:
tp = cm_logistic[0][0]
tn = cm_logistic[1][1]
fn = cm_logistic[0][1]
fp = cm_logistic[1][0]

In [31]:
print("True Positive", tp)
print("True Negative", tn)
print("False Negative", fn)
print("False Postive", fp)

True Positive 26
True Negative 29
False Negative 6
False Postive 0


In [32]:
accuracy_logistic = (tp + tn) / (tp+tn+fp+fn)
accuracy_logistic

0.9016393442622951

In [33]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [34]:
print("For Logistic Regression Model")
print("-"*50)
cml = confusion_matrix(y_test, y_pred1)
cdf = pd.DataFrame(cml, columns=list(range(0,2)))
print(cdf)
print("-"*50)
print(f"Precision: {precision_score(y_test, y_pred1)}")
print(f"Recall: {recall_score(y_test, y_pred1)}")
print(f"F1 Score: {f1_score(y_test, y_pred1)}")

For Logistic Regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision: 0.8285714285714286
Recall: 1.0
F1 Score: 0.90625


In [35]:
print("For Decision Tree Model")
print("-"*50)
cmd = confusion_matrix(y_test, y_pred2)
cdf = pd.DataFrame(cmd, columns=list(range(0,2)))
print(cdf)
print("-"*50)
print(f"Precision: {precision_score(y_test, y_pred2)}")
print(f"Recall: {recall_score(y_test, y_pred2)}")
print(f"F1 Score: {f1_score(y_test, y_pred2)}")

For Decision Tree Model
--------------------------------------------------
    0   1
0  24   8
1   2  27
--------------------------------------------------
Precision: 0.7714285714285715
Recall: 0.9310344827586207
F1 Score: 0.84375


In [36]:
precision_score(y_test, y_pred1, average=None)

array([1.        , 0.82857143])

In [37]:
recall_score(y_test, y_pred1, average=None)

array([0.8125, 1.    ])

In [38]:
precision_score(y_test, y_pred2, average=None)

array([0.92307692, 0.77142857])

In [39]:
recall_score(y_test, y_pred2, average=None)

array([0.75      , 0.93103448])