In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open("models/ohe_sex.pkl", "rb"))
ohe_embarked = pickle.load(open("models/ohe_embarked.pkl","rb"))
clf = pickle.load(open("models/clf.pkl", "rb"))

# User Input

In [4]:
test_input = np.array([3, 'female', 28.0, 0, 0, 31, 'C'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[3, 'female', 28.0, 0, 0, 31, 'C']], dtype=object)

In [6]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\atifs\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [7]:
test_input_sex

array([[1., 0.]])

In [8]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [9]:
test_input_embarked

array([[1., 0., 0.]])

In [10]:
test_input_age = test_input[:,2].reshape(1,1)

In [11]:
test_input_transformed = np.concatenate((test_input[:, [0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [12]:
test_input_transformed.shape

(1, 10)

In [13]:
clf.predict(test_input_transformed)

array([0], dtype=int64)